# Generated by Django 5.1.1 on 2024-09-25 10:55

import contacts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_alter_contact_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='photo',
            field=models.ImageField(default='images/default.jpg', upload_to=contacts.models.rename_image),
        ),
    ]
